### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by lzk98** [dimiboeckaerts/PhageRBPdetection#2]
Hi 
I use `python RBPdetect_standalone.py --dir /directory/with/files --hmmer_path /path/to/hmmer` to run the `data/examples.fasta`(sequences.fasta) .The result following:
preds
0
0
0
I want to know if the results are accurate?

```
miniconda3/envs/phageRBP/lib/python3.8/site-packages/xgboost/compat.py:31: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
Running HMM predictions...
Scanning the proteins: 100%|██████████████████████| 3/3 [00:00<00:00, 22.33it/s]
Computing embeddings... (this can take a while on a CPU)
Some weights of the model checkpoint at/.cache/bio_embeddings/prottrans_bert_bfd/model_directory were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
100%|█████████████████████████████████████████████| 3/3 [00:04<00:00,  1.42s/it]
Running XGBoost predictions...
/miniconda3/envs/phageRBP/lib/python3.8/site-packages/xgboost/data.py:192: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
Traceback (most recent call last):
  File "RBPdetect_standalone.py", line 252, in <module>
    score_xgb = xgb_saved.predict_proba(embeddings)[:,1]
  File "/miniconda3/envs/phageRBP/lib/python3.8/site-packages/xgboost/sklearn.py", line 1016, in predict_proba
    test_dmatrix = DMatrix(X, base_margin=base_margin,
  File "/miniconda3/envs/phageRBP/lib/python3.8/site-packages/xgboost/core.py", line 500, in __init__
    handle, feature_names, feature_types = dispatch_data_backend(
  File "/miniconda3/envs/phageRBP/lib/python3.8/site-packages/xgboost/data.py", line 539, in dispatch_data_backend
    return _from_pandas_df(data, enable_categorical, missing, threads,
  File "/miniconda3/envs/phageRBP/lib/python3.8/site-packages/xgboost/data.py", line 242, in _from_pandas_df
    data, feature_names, feature_types = _transform_pandas_df(
  File "/miniconda3/envs/phageRBP/lib/python3.8/site-packages/xgboost/data.py", line 207, in _transform_pandas_df
    raise ValueError(msg + ', '.join(bad_fields))
ValueError: DataFrame.dtypes for data must be int, float, bool or categorical.  When
                categorical type is supplied, DMatrix parameter
                `enable_categorical` must be set to `True`.ID
```
I would like to know the version number of all dependent packages in your environment, especially xgboost.
Thank you

**Comment by dimiboeckaerts** [comment]
Hi! Thanks for reaching out. The examples.fasta file contains three RBPs that are recognized by the collection of HMMs, so they should all be predicted as 1's. I think the problem is my unfortunate naming: the file itself is `examples.fasta` but the standalone version requires the file being named `sequences.fasta`. Perhaps that is the reason that you don't get the correct predictions? I will adjust this file name to avoid further confusion. Let me know if I can help anywhere else.
