### ISSUE TITLE
Trouble using Stand alone pipelines

### ISSUE THREAD

**Issue by JoshuaIszatt** [dimiboeckaerts/PhageRBPdetection#3]
# Hi Dimi, I'm trying to use the standalone pipline but I'm getting this error:

(hermes) jiszatt@tki-hohpc-2022:/SCRATCH/RBP_prediction/PhageRBPdetection$ python RBPdetect_standalone.py --dir /SCRATCH/RBP_test --hmmer_path /SCRATCH/hmmer-3.3.2
Running HMM predictions...
Scanning the proteins: 100%|███████████████████████████████████████████| 3/3 [00:00<00:00, 10.64it/s]
Computing embeddings... (this can take a while on a CPU)
prottrans_bert_bfd.zip: 0.00B [00:01, ?B/s]
Traceback (most recent call last):
  File "RBPdetect_standalone.py", line 243, in <module>
    embeddings = compute_protein_embeddings(fasta_file)
  File "RBPdetect_standalone.py", line 185, in compute_protein_embeddings
    embedder = ProtTransBertBFDEmbedder()
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/site-packages/bio_embeddings/embed/prottrans_bert_bfd_embedder.py", line 23, in __init__
    super().__init__(**kwargs)
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/site-packages/bio_embeddings/embed/embedder_interfaces.py", line 59, in __init__
    model=self.name, directory=directory
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/site-packages/bio_embeddings/utilities/remote_file_retriever.py", line 72, in get_model_directories_from_zip
    request.urlretrieve(url, filename=file_name, reporthook=t.update_to)
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/SCRATCH/.mini/envs/hermes/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 406: Not Acceptable

# I am using an environment produced with:

name: hermes
channels:
  - default
  - anaconda
  - conda-forge
  - bioconda
  - 
dependencies:
  - python==3.8.0
  - setuptools
  - jsonnet
  - numpy
  - pandas
  - biopython
  - tqdm
  - xgboost
  - python-devtools
  - gcc
  - gxx
  - jupyter

  pip install bio-embeddings[all]
  pip install overrides==3.1.0

# I hope this makes sense (apologies, I'm very new to github and bioinformatics). Thanks, Josh.

**Comment by dimiboeckaerts** [comment]
Hi Josh! Hmm I haven't encountered that error myself, but there are some issues on the bio-embeddings GitHub repository that deal with it, perhaps these can help you solve this:
https://github.com/sacdallago/bio_embeddings/issues/163
https://github.com/sacdallago/bio_embeddings/issues/156

Hope this helps!
