### ISSUE TITLE
Option to run V3 with CPU

### ISSUE THREAD

**Issue by ilyavs** [dimiboeckaerts/PhageRBPdetection#6]
Hi,
I tried running V3 on a machine without a GPU and got this error:
```Traceback (most recent call last):
  File "PhageRBPdetection/PhageRBPdetect_v3/PhageRBPdetect_v3_inference.py", line 43, in <module>
    model.eval().cuda()
  File "/usr/local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2569, in cuda
    return super().cuda(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 918, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 918, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled```

Can you allow running with a CPU only? Will it be feasible?
Thanks,
Ilya.

**Comment by dimiboeckaerts** [comment]
Hi Ilya! Great comment, I indeed enabled the _inference.py file to run on the GPU by setting `model.eval().cuda()`. I adapted the script so it automatically detects which device is available and runs with what that. I pushed the updates to the main branch, please let me know if you have any more issues! You should be able to run it on a CPU as well, albeit more slowly (and perhaps not for extremely long sequences).

Kind regards
**Dimi**
